Repository Open-Momentum/inmobilaria-bonpland, pull requests merged in 2025-03, with the labels that each got.

#3 Instalaciones principales para el proyecto frontend
  README.md
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/components.json
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/(auth)/sign-in/page.tsx
  frontend/src/app/(auth)/sign-up/page.tsx
  frontend/src/app/(main)/layout.tsx
  frontend/src/app/(main)/profile/page.tsx
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/lib/utils.ts
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: enhancement

#6 Interfaces de usuario
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/logo-bonpland.svg
  frontend/src/app/(auth)/auth/reset-password/page.tsx
  frontend/src/app/(auth)/auth/sign-in/page.tsx
  frontend/src/app/(auth)/auth/sign-up/page.tsx
  frontend/src/app/(auth)/sign-in/page.tsx
  frontend/src/app/(auth)/sign-up/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/atoms/section.tsx
  frontend/src/components/landing/landing-footer.tsx
  frontend/src/components/landing/landing-header.tsx
  frontend/src/components/landing/landing-hero-section.tsx
  frontend/src/components/landing/landing-news.tsx
  frontend/src/components/landing/landing-recommended-properties.tsx
  frontend/src/components/molecules/news-card.tsx
  frontend/src/components/molecules/property-card.tsx
  frontend/src/components/molecules/property-filter.tsx
  frontend/src/components/molecules/requirements-section.tsx
  frontend/src/components/molecules/theme-toggle.tsx
  frontend/src/components/providers.tsx
  frontend/src/components/theme-provider.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/radio-group.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/slider.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/lib/consts.ts
Labels: enhancement, ready for review

#12 CRUD de inmuebles
  backend/src/main/java/idforideas/bonpland/config/SecurityConfig.java
  backend/src/main/java/idforideas/bonpland/controller/InmuebleController.java
  backend/src/main/java/idforideas/bonpland/dto/inmuebles/InmuebleDTO.java
  backend/src/main/java/idforideas/bonpland/dto/inmuebles/InmuebleResponseDTO.java
  backend/src/main/java/idforideas/bonpland/dto/usuarios/UsuarioCompletoDTO.java
  backend/src/main/java/idforideas/bonpland/dto/usuarios/UsuarioRequest.java
  backend/src/main/java/idforideas/bonpland/entities/Inmueble.java
  backend/src/main/java/idforideas/bonpland/entities/Usuario.java
  backend/src/main/java/idforideas/bonpland/exception/InmuebleNoEncontradoException.java
  backend/src/main/java/idforideas/bonpland/exception/UsuarioSinPermisoException.java
  backend/src/main/java/idforideas/bonpland/handler/GlobalExceptionHandler.java
  backend/src/main/java/idforideas/bonpland/mapper/impl/InmuebleMapper.java
  backend/src/main/java/idforideas/bonpland/mapper/impl/InmuebleRespuestaMapper.java
  backend/src/main/java/idforideas/bonpland/repository/InmuebleRepository.java
  backend/src/main/java/idforideas/bonpland/service/InmuebleService.java
  backend/src/main/java/idforideas/bonpland/service/impl/InmuebleServiceImpl.java
  backend/src/main/resources/db/migration/V1__create_schema.sql
  backend/src/test/java/idforideas/bonpland/controller/InmuebleControllerTest.java
  backend/src/test/java/idforideas/bonpland/controller/UsuarioControllerTest.java
  backend/src/test/java/idforideas/bonpland/service/InmuebleServiceImplTest.java
  backend/src/test/java/idforideas/bonpland/utils/TestUtil.java
Labels: ready for review
